[package]
name = "mini-rusaint"

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["cookies", "json"] }
derive_builder = "0.20.2"
regex = "1.11.1"
dotenv = "0.15.0"
thiserror = "2.0.9"
scraper = "0.22.0"
